### ISSUE TITLE
Undefined index: out when leaving animation is off

### ISSUE THREAD

**Issue by ghost** [JoomTools/plg_system_jtanimsition#3]
With following settings and master download of today I get a warning

```
Notice: Undefined index: out in ...\plugins\system\jtanimsition\jtanimsition.php on line 258
```

![when-leaving-off](https://cloud.githubusercontent.com/assets/11038612/9076575/76a94996-3b24-11e5-888e-daea381258b3.png)

**Comment by ghost** [comment]
Addition to post above: When I enable "Component output" a second PHP notice

```
Notice: Undefined index: out in plugins\system\jtanimsition\jtanimsition.php on line 263
```

**Comment by degobbis** [comment]
Thanks for Your tests.
I cleared the PHP notices and change some logicals. You're welcome to retest the plugin.

PS. This plugin allows You to override global settings in each menuitem.
