### ISSUE TITLE
fatal error member functon

### ISSUE THREAD

**Issue by micker** [JoomTools/plg_system_jtanimsition#4]
hello i try jt animstion on j3.4.5 but when i try to edit a module or using some ajax feature i have this error
fatal error : call to member function get() on non-objet in /...../jtamsition.php on line79
do you have an idea ?

**Comment by degobbis** [comment]
Hello, unfortunately it was not possible for me to reproduce the error. Can you please describe the process step by step as it comes to the failure?
You could try to change the order of the plugin and to load it as first. Maybe it solves the problem.

**Comment by degobbis** [comment]
I've released a new version, hope it will solve Your problem too.
